name: Build and Push to Docker Hub

on:
  push:
    branches: [main]   # Only trigger on main branch pushes
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx # modern Docker builder that supports multi-platform builds
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
         printf '%s' "$DOCKERHUB_TOKEN" | docker login docker.io -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile  # change if your Dockerfile has a different name or path
          push: true
          tags: Kirthi18/customer-churn-prediction:latest
